name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20.5
      - uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1

      - name: Install dependencies
        run: bun install

      - name: Lint files
        run: bun run lint

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20.5
      - uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1

      - name: Install dependencies
        run: bun install

      - name: Generate files
        run: bun run build
